import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { TbsGeneratedModule, TbsGeneratedSharedModule } from './generated/module';
import { TbsValidator, registerValidationChecks } from './tbs-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type TbsAddedServices = {
    validation: {
        TbsValidator: TbsValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type TbsServices = LangiumServices & TbsAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const TbsModule: Module<TbsServices, PartialLangiumServices & TbsAddedServices> = {
    validation: {
        TbsValidator: () => new TbsValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createTbsServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Tbs: TbsServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        TbsGeneratedSharedModule
    );
    const Tbs = inject(
        createDefaultModule({ shared }),
        TbsGeneratedModule,
        TbsModule
    );
    shared.ServiceRegistry.register(Tbs);
    registerValidationChecks(Tbs);
    return { shared, Tbs };
}
